import { useState } from 'react';
import { TablaMaterial } from '@components/TablaMaterial';
import { ModalMaterial } from '@components/ModalMaterial';
import { PrivateRoute } from '@components/PrivateRoute';
import { Layout } from '@layouts/Layout';
import Head from 'next/head';
import { useQuery } from '@apollo/client';
import { Material } from '@prisma/client';
import { GET_MATERIALS_BY_USER } from '@graphql/client/materials';

const Material = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);

  const { data, loading, error, refetch } = useQuery<{
    materialsByUser: Material[];
  }>(GET_MATERIALS_BY_USER, {
    fetchPolicy: 'cache-first',
  });

  const handleOpenModal = () => {
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    refetch();
  };

  return (
    <PrivateRoute>
      <Layout>
        <Head>
          <title>Materiales</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <>
          <div className='w-[460px] text-center font-poppins text-5xl'>
            Materiales
          </div>
          <div className='flex space-x-[526px] pt-[77px]'>
            <button
              onClick={handleOpenModal}
              className='h-[65px] w-[226px] rounded-xl bg-[#004737] font-poppins text-xl text-white shadow-md transition duration-500 ease-in-out hover:bg-[#007f5f]'
            >
              Agregar Material
            </button>
          </div>
          <TablaMaterial
            data={data?.materialsByUser}
            loading={loading}
            error={error}
          />
        </>
        <ModalMaterial isOpen={isModalOpen} onClose={handleCloseModal} />
      </Layout>
    </PrivateRoute>
  );
};

export default Material;
