import { useState } from 'react';
import { TablaMaterial } from '@components/TablaMaterial';
import { ModalMaterial } from '@components/ModalMaterial';
import { PrivateRoute } from '@components/PrivateRoute';
import { Layout } from '@layouts/Layout';
import Head from 'next/head';
import { useQuery } from '@apollo/client';
import { Material } from '@prisma/client';
import { GET_MATERIALS_BY_USER } from '@graphql/client/materials';

const Material = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);

  const { data, loading, error, refetch } = useQuery<{
    materialsByUser: Material[];
  }>(GET_MATERIALS_BY_USER, {
    fetchPolicy: 'cache-first',
  });

  const handleOpenModal = () => {
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    refetch();
  };

  return (
    <PrivateRoute>
      <Layout>
        <Head>
          <title>Materiales</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        {/* TITLE */}
        <div className='pb-3 pt-3 text-center font-poppins text-3xl md:text-5xl'>
          Materiales
        </div>

        {/* BUTTONS */}
        <div className='mt-6'>
          <button
            onClick={handleOpenModal}
            className='h-12 rounded-xl bg-[#004737] px-4 font-poppins text-xl text-white shadow-md transition duration-500 ease-in-out hover:bg-[#007f5f]'
          >
            Agregar Material
          </button>
        </div>

        {/* TABLE */}
        <div className='flex w-full items-center justify-center'>
          <TablaMaterial
            data={data?.materialsByUser}
            loading={loading}
            error={error}
          />
        </div>

        <ModalMaterial isOpen={isModalOpen} onClose={handleCloseModal} />
      </Layout>
    </PrivateRoute>
  );
};

export default Material;
